### ISSUE TITLE
关于Github Actions LuaTeX使用LaTeXmkrc文件编译无法正确获取特定时区时间的问题

### ISSUE THREAD

**Issue by Mikachu2333** [CTeX-org/forum#328]
### 检查清单

- [X] 我已在 issues 中进行搜索（包括已关闭的问题）

### 操作系统

ubuntu-latest

### TeX 发行版

texlive-full:20240501

### 描述问题

如题，在自己的电脑上编译不会出现该问题，但是使用GitHub Actions就会复现，并且怎么也修不好，下面详述。

## 目的：
1. 在文档中获取到编译时间
2. 将编译时间显示为形如 `2024.08.16 20:21:44 GMT+08:00` 的样式
3. 相关代码应当在任意时区的设备上正确将时间转换为东八区时间（而不是修改系统时间或时区）
4. 尽量不要通过latex显式执行外部程序解决（尽量用package包装后的接口）

## Env： 
**本地环境：**

- 本地系统配置：
```
操作系统： Debian GNU/Linux 12
KDE Plasma 版本： 5.27.5
KDE 程序框架版本： 5.103.0
Qt 版本： 5.15.8
内核版本： 6.1.0-23-amd64 (64 位)
图形平台： X11
处理器： 8 × 11th Gen Intel® Core™ i5-1135G7 @ 2.40GHz
内存： 15.4 GiB 内存
图形处理器： Mesa Intel® Xe Graphics
制造商： LENOVO
产品名称： 20WE
系统版本： ThinkBook 14s Yoga ITL
```

- 本地其他环境：

完整安装了texlive2024、openjdk-17-jre-headless、openjdk-17-jre、nvidia-openjdk-8-jre、python3.11.2、Rust环境（仅linux unknown x64 stable gnu target）、gnu套件

**Github actions环境：**
- xelatex: 仅使用了 `xu-cheng/texlive-full:20240501`
- luatex: `xu-cheng/texlive-full:20240501`、`actions/setup-java@v4`的`temurin`发行的21版

### xelatex正常编译
（无论本地还是github actions都正常，最后一个编译正常的链接见 https://github.com/Mikachu2333/sdsmu_welcome_tex/actions/runs/10183904493 ）

使用xelatex联合latexmkrc可以**正常获取时间**的，GitHub Actions与latex文件核心代码如下（此时GitHub Actions未配置jre环境也能正常运行）：

参考commit（只需看`main.tex`、`build_preview.yaml`、`latexmkrc`文件）： https://github.com/Mikachu2333/sdsmu_welcome_tex/tree/44159691b15b946ae0173933e05f2e55cc9c767c

**MWE见下方“正常MWE”**

### 更换luaTeX编译后本地正常，GitHub actions错误取到了格林尼治时间（0时区）
如上，无法正确获取时间，总是获取到0时区（格林尼治时间），并且无论texosquery是否引用、jre环境是否配置均无影响，无报错

参考commit：

## Xelatex正常MWE：
**yml核心内容**
```yml
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@3.2.0
        with:
          docker_image: ghcr.io/xu-cheng/texlive-full:20240501
          root_file: main.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          args: |
            -synctex=1 
            -interaction=nonstopmode 
            -halt-on-error 
            -file-line-error
          extra_fonts: |
            ./*.otf
            ./*.ttf
```

**latex核心内容**
```latex
% !TeX encoding = UTF-8
% !TEX TS-program = xelatex
\documentclass[a4paper,12pt,UTF8]{ctexrep}
\usepackage{texosquery}%仅当为xelatex编译时使用，这玩意应当在actios中配置jre环境的，但是没配置也没出事就很怪
\usepackage{datetime2}

\newcommand{\CurrentCustomTime}{
    \DTMsavenow{Compiled_time}%保存编译时间
    \DTMfetchyear{Compiled_time}.%
    \DTMtwodigits{\DTMfetchmonth{Compiled_time}}.%
    \DTMtwodigits{\DTMfetchday{Compiled_time}}\quad%
    \DTMtwodigits{\DTMfetchhour{Compiled_time}}:%
    \DTMtwodigits{\DTMfetchminute{Compiled_time}}:%
    \DTMtwodigits{\DTMfetchsecond{Compiled_time}}\quad%
    GMT\DTMfetchTZhour{Compiled_time}:\DTMfetchTZminute{Compiled_time}
}

\begin{document}
\CurrentCustomTime
\end{document}
  ```

**latexmkrc文件内容：**
```latexmkrc
$ENV{'TZ'}='Asia/Shanghai';
```

**编译命令：**
```
latexmk -synctex=1 -interaction=nonstopmode -shell-escape -halt-on-error -file-line-error -xelatex "%DIR%/main.tex"
```

## luatex异常MWE（本地正常，GitHub Actions异常）
**有texosquery和jre的版本见此：**
https://github.com/Mikachu2333/sdsmu_welcome_tex/actions/runs/10421407234
https://github.com/Mikachu2333/sdsmu_welcome_tex/tree/41dbbc8349e2883ab3c22fd93ea37e8041137fb4

**无texosquery和jre的版本见此**
https://github.com/Mikachu2333/sdsmu_welcome_tex/actions/runs/10421321719
https://github.com/Mikachu2333/sdsmu_welcome_tex/tree/a4a0609cd47862a394dc99a544eb525cbf508dd5

### 链接

无

### 其他信息

我尝试了jre配置与texosquery的引用与否

我还看了datetime2的说明文档然而并无所获

我看了latexmk的文档但是没明白为什么我的rc文件无法指定时区，明明xelatex的时候是正常的，luatex我自己本地编译也是正常的，就luatex线上编译炸了

### 附件

所有超长的log文件（因线上的字体配置导致）均请参见actions的日志，不在此处附上
